### ISSUE TITLE
Epic Issue B2: Backend Controller for CRUD operations for announcements

### ISSUE THREAD

**Issue by anguyen412** [ucsb-cs156-w24/proj-happy-cows-w24-4pm-4#20]
Backend Issue 2 of #1
Should be started after finishing #19 

Developer Story:

* As an developer
* I have access to backend endpoints (through swagger) for CRUD operations for the Announcements table
* So that I can build future features using this table

Acceptance Criteria:

- [x] There is a POST endpoint to create new announcements
- [x] The POST endpoint to create new announcements rejects POST values with invalid data (e.g. a commonsId for a commons that doesn't exist, announcements with empty text, end date that is before start date, start date blank)
- [x] The POST endpoint allows end date to be blank, in which case it is stored as NULL in the database
- [x] There is a GET endpoint to get all announcements for a specified commons
- [x] There is a GET endpoint to get an announcement by its individual id number
- [x] There is a PUT endpoint that allows updating the announcement. It performs the same validations as the POST endpoing.
- [x] There is a DELETE endpoint that allows deleting an announcement
