### ISSUE TITLE
EPIC: Admin can turn chat on/off (1): showChat field and default value

### ISSUE THREAD

**Issue by hyi96** [ucsb-cs156-w24/proj-happy-cows-w24-4pm-4#25]
### Description
A PR that adds the fields to the entity with a default value of true (this preserves existing functionality, since at first it's just an extra field in the table, hanging out with a default value of true, that isn't being looked at in the code anywhere else. Make sure that creating a new commons or editing an existing one still works.)

### Acceptance Criteria
- [x] showChat field is added with default value set to true.
- [x] creating a new commons or editing an existing one still works.
- [x] unit tests for verifying default value of showChat is true.
- [x] PR for merging into EPIC-CHAT-ON-OFF-MAIN.
