### ISSUE TITLE
EPIC: Admin can turn chat on/off (2): effective backend

### ISSUE THREAD

**Issue by hyi96** [ucsb-cs156-w24/proj-happy-cows-w24-4pm-4#26]
### Description
A PR to make the backend endpoints respect the value of the field, meaning they will respond for regular users if/only if the showChat field is true, and return 403 if the field is false, but admins get responses no matter what the value of the field is. You won't be able to test interactively, but you can write unit tests that will manually set up a commons where showChat is false for purposes of the unit test. Again, at this point, no users facing functionality has changed, since there is no interactive way to set the chat field either through the backend or the frontend.

### Prerequisites
- [x] https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/31 has been merged into EPIC-CHAT-ON-OFF-MAIN
- [x] create a new branch from EPIC-CHAT-ON-OFF-MAIN

### Acceptance Criteria
- [ ] For admins, all endpoints of ChatMessageController always respond no matter what the value of showChat is.
- [ ] For users, get and post endpoints of ChatMessageController return 403 if showChat is false. 
- [ ] backend unit tests for the previous 2 criteria. 
- [ ] PR for merging into EPIC-CHAT-ON-OFF-MAIN.
