### ISSUE TITLE
EPIC: Admin can turn chat on/off (3): backend POST/PUT

### ISSUE THREAD

**Issue by hyi96** [ucsb-cs156-w24/proj-happy-cows-w24-4pm-4#27]
### Description
Next, a PR adding the ability to set the field to true or false when doing the POST and PUT operations on the backend for commons. Now, as an admin, you can test interactively by using swagger to change the value (though you still can't do it via the normal user interface.)

### Acceptance Criteria
- [x] showChat field can be set in POST operation in swagger.
- [x] showChat field can be set in PUT operation in swagger.
- [x] PR for merging into EPIC-CHAT-ON-OFF-MAIN.
