### ISSUE TITLE
RM - EPIC: Admin can turn chat on/off (4): frontend CommonsForm

### ISSUE THREAD

**Issue by hyi96** [ucsb-cs156-w24/proj-happy-cows-w24-4pm-4#28]
### Description
A PR to add the checkbox to the CommonsForm so that you can change the value of showChat with a checkbox similar to that for showLeaderboard.

### Prerequisites
- [x] https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/31 has been merged into EPIC-CHAT-ON-OFF-MAIN
- [x] create a new branch based on the latest EPIC-CHAT-ON-OFF-MAIN

### Acceptance Criteria
- [x] have a checkbox similar to that for showLeaderboard for showChat in CommonsForm.
- [x] checkbox for showChat calls API correctly and the correct setting is reflected in the database.
- [x] add frontend unit tests in CommonsForm.test.js and AdminCreateCommonsPage.js if necessary
- [x] update storybook
- [x] PR for merging into EPIC-CHAT-ON-OFF-MAIN.
