### ISSUE TITLE
EPIC: Admin can turn chat on/off (BONUS): add showChat column to CommonsTable

### ISSUE THREAD

**Issue by hyi96** [ucsb-cs156-w24/proj-happy-cows-w24-4pm-4#29]
### Description
Anytime after (1), though it makes more sense after (3) or after (4), you can add the showChat field to the CommonsTable that admins use to see all of the data for a commons. This is optional, because that table doesn't necessarily have to show everything; admins can click "Edit" if they want to see all of the fields for the commons.

### Acceptance Criteria
- [x] showChat field is included in CommonsTable
- [x] admins can see showChat values from listcommons page
- [x] related frontend unit tests
- [x] update storybook
- [x] PR for merging into EPIC-CHAT-ON-OFF-MAIN.
