### ISSUE TITLE
EPIC: Admin can turn chat on/off (5): frontend chat button display

### ISSUE THREAD

**Issue by hyi96** [ucsb-cs156-w24/proj-happy-cows-w24-4pm-4#32]
### Description
A PR to hide or display the chat button for a user depending on the value of showChat of a Commons.

### Prerequisites
- [x] https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/pull/31 has been merged into EPIC-CHAT-ON-OFF-MAIN
- [x] create a new branch from EPIC-CHAT-ON-OFF-MAIN

### Acceptance Criteria
- [ ] For admins, Chat button always displays no matter what the value of showChat is.
- [ ] Chat button should be hidden from users when showChat is false.
- [ ] storybook for when showChat is true/false for users.
- [ ] frontend unit tests.
- [ ] PR for merging into EPIC-CHAT-ON-OFF-MAIN.

### Testing 
- [ ] npm test
- [ ] npm run coverage
- [ ] npx stryker run
- [ ] npx eslint --fix src
